export { default as Navbar } from "./Navbar";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Contact } from "./Contact";
export { default as Sidebar } from "./Sidebar";
export { default as RightSidebar } from "./RightSideBar";
export { default as Projects} from "./Projects";
export { default as Project1} from "./Project1";
export { default as Project2} from "./Project2";
export { default as Project3} from "./Project3";
export { default as Project4} from "./Project4";
export { default as Project5} from "./Project5";